name: docsgpt-oss
services:

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user           # Default username (you can change this)
      POSTGRES_PASSWORD: password   # Default password (you can change this)
      POSTGRES_DB: docsgpt         # Default database name (you can change this)
    ports:
      - 5432:5432                  # Exposes PostgreSQL on port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Named volume for persistent storage

volumes:
  mongodb_data_container:
  postgres_data:

