"""Added additional coloumns for refresh_tokens

Revision ID: 4822c3a8f17b
Revises: 2958cbe5f5d5
Create Date: 2025-12-19 22:25:58.532164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4822c3a8f17b'
down_revision = '2958cbe5f5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_jti', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('device_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_refresh_tokens_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_parent_jti'), ['parent_jti'], unique=False)
        batch_op.create_foreign_key(None, 'refresh_tokens', ['parent_jti'], ['jti'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_parent_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_device_id'))
        batch_op.drop_column('device_id')
        batch_op.drop_column('used_at')
        batch_op.drop_column('parent_jti')

    # ### end Alembic commands ###
